apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sre-challenge-statefulset
  labels:
    app: sre-challenge
spec:
  selector:
    matchLabels:
      app: sre-challenge
  replicas: 5
  minReadySeconds: 3
  template:
    metadata:
      labels:
        app: sre-challenge
    spec:
      containers:
        - name: sre-challenge
          image: jjpebesma/warpnet-sre-challenge:latest
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sre-challenge-secret
                  key: password
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sre-challenge-secret
                  key: secret-key
            - name: PROXY
              value: "true"
          ports:
            - containerPort: 5000
              name: web
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: "/app/data"
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: sre-challenge-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sre-challenge
  name: sre-challenge-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sre-challenge-service
  labels:
    app: sre-challenge
spec:
  selector:
    app: sre-challenge
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-challenge-ingress
  labels:
    app: sre-challenge
spec:
  ingressClassName: nginx
  rules:
    - host: sre-challenge.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sre-challenge-service
                port:
                  number: 5000